create table if not exists orders (
  id text primary key,
  customer jsonb not null,
  package jsonb not null,
  status text not null,
  created_at timestamptz not null,
  estimated_delivery text,
  source text
);

create table if not exists expenses (
  id text primary key,
  amount numeric not null,
  purpose text not null,
  order_id text,
  created_at timestamptz not null
);

create table if not exists analytics_events (
  id text primary key,
  type text not null,
  metadata jsonb,
  created_at timestamptz not null
);

create table if not exists admin_settings_snapshots (
  id bigint generated by default as identity primary key,
  settings jsonb not null,
  created_at timestamptz not null
);
